AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Description: API for Sending Emails via SNS

Resources:
  # API Gateway
  EmailApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: EmailAPI
      ProtocolType: HTTP
      CorsConfiguration:
        AllowCredentials: false
        AllowHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowOrigins:
          - '*'
        ExposeHeaders:
          - Date
          - x-api-id
        MaxAge: 300

  # API Gateway Integration
  EmailApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref EmailApiGateway
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub
        - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SendEmailLambda.Arn}/invocations
        - SendEmailLambda: !GetAtt SendEmailLambda.Arn
      PayloadFormatVersion: '2.0'

  # API Gateway Route
  EmailApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref EmailApiGateway
      RouteKey: POST /send-email
      Target: !Sub integrations/${EmailApiIntegration.IntegrationId}

  # API Gateway Stage
  EmailApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref EmailApiGateway
      StageName: prod
      AutoDeploy: true
      DefaultRouteSettings:
        ThrottlingBurstLimit: 5
        ThrottlingRateLimit: 10

  # Lambda Function
  SendEmailLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt EmailLambdaRole.Arn
      CodeUri: send-email/
      Runtime: nodejs22.x
      MemorySize: 128
      Timeout: 5
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref EmailSNSTopic

  # SNS Topic
  EmailSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: email
          Endpoint: samuelgiordano@live.com

  # IAM Role for Lambda
  EmailLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "EmailLambdaPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "apigateway:POST"
                  - "apigateway:PUT"
                  - "apigateway:DELETE"
                  - "apigateway:GET"
                  - "apigateway:PATCH"
                  - "lambda:InvokeFunction"
                  - "lambda:GetFunctionConfiguration"
                  - "lambda:UpdateFunctionCode"
                  - "lambda:UpdateFunctionConfiguration"
                  - "sns:Publish"
                Resource: "*"

  # API Gateway Deployment
  EmailApiGatewayDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref EmailApiGateway
    DependsOn:
      - EmailApiRoute
      - EmailApiIntegration

  # Lambda Invoke Permission
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt SendEmailLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${EmailApiGateway}/*/POST/send-email
